### ISSUE TITLE
If Custom Header is added and UDP length argument is passed as input, what should be UDP length configured in ixNetwork user specified length or auto?

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#107]
If Custom Header is added and UDP length argument is passed as input, what should be UDP length configured in ixNetwork user specified length or auto?

**Comment by ashutshkumr** [comment]
UDP length field, if assigned explicitly by user, will remain set to assigned value (wireshark might flag if UDP length is incorrect).
If not explicitly assigned, it should automatically be assigned correct value by the implementation (e.g. almost guarantee that length will be correct).

+@ajbalogh for context.
