### ISSUE TITLE
A few classes in abstract_open_traffic_generator package has same name so, people need to use tricky technique to include namesake classes in the code. 

### ISSUE THREAD

**Issue by abhijit-dhar** [open-traffic-generator/ixnetwork#11]
Please find the extract form a test cases below: I have shown the conflicting names in **bold**

from abstract_open_traffic_generator.port import Port, OneHundredGbe, Layer1
from abstract_open_traffic_generator.device import DeviceGroup, Device
from abstract_open_traffic_generator.device import **Ethernet**, **Vlan**, **Ipv4**
from abstract_open_traffic_generator.device import **Pattern**
from abstract_open_traffic_generator.config import Config
from abstract_open_traffic_generator.flow import DeviceEndpoint, Endpoint, Flow, Header, Size, Rate,\
    Duration, Fixed, PortEndpoint, PfcPause, Counter, Random

################################################################################
# COMMENTS
# 1. Some classes defined "abstract_open_traffic_generator.device" and
#    "abstract_open_traffic_generator.flow" has the same name. Like Ipv4, Vlan,
#    Ethernet, Pattern. Different name required.
################################################################################
from abstract_open_traffic_generator.flow import **Pattern** as PATTERN
from abstract_open_traffic_generator.flow import **Ipv4** as IPV4
from abstract_open_traffic_generator.flow import **Vlan** as VLAN
from abstract_open_traffic_generator.flow import **Ethernet** as ETHERNET
from abstract_open_traffic_generator.flow_ipv4 import Priority, Dscp

**Comment by ashutshkumr** [comment]
Addressed in https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/open-traffic-generator/models/master/artifacts/openapi.yaml
