### ISSUE TITLE
Inconsistency in datatype for step variable between Counter & Random 

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#116]
In `Counter` pattern the step variable datatype is `str` whereas in `Random` pattern step variable is `int|float` . Not able to get why the variable is defined with different datatypes for different Patterns.

**Comment by ashutshkumr** [comment]
@ANISH-GOTTAPU please check the spec in `models` repository. If you see the inconsistency in spec between the two, please raise an issue there and reference this issue.

@ajbalogh FYI

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
