### ISSUE TITLE
Add test for UDP header with Random Pattern for UDP src,dst port

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#117]
- Add new test script inside tests/udp/
- For each pattern type in Random
       - Provide non-default counter pattern values for src port, dst port
       - Validate that src port, dst port are as expected from captured frame

**Comment by ajbalogh** [comment]
I disagree with this approach as it increases the build time with no added benefit. A better approach is to set the configuration and validate using restpy. These should be considered tests for this repo and not part of the overall public tests.

**Comment by ashutshkumr** [comment]
Thanks for raising this @ajbalogh . restpy approach was also initially suggested by @Rangababu-R and @ANISH-GOTTAPU .

We're currently evaluating what are the tests we should validate simply using restpy and if it makes sense to move the rest out to a separate repo.

@winstonliu1111 @ankur-sheth FYI.

**Comment by ANISH-GOTTAPU** [comment]
Closed with #113
