### ISSUE TITLE
Traffic apply error on concurrent test if traffic is not stopped in previous test

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#138]
Steps to reproduce
1) Create a test and send continuous traffic and don't stop the traffic.
2) update the traffic to fixed duration 
`flow.Duration(flow.FixedPackets(packets='1000'))`
3) Run the test again to get traffic apply error

I assume if traffic is running, the stop should be handled internally, correct me if my understanding is wrong

**Comment by ajbalogh** [comment]
Nothing should be handled internally. If the user doesn't want to stop traffic as part of the test or infrastructure then the package should raise an exception.

**Comment by ashutshkumr** [comment]
If the previous test timed out or errored out due to some underlying issue and skipped the `stop traffic` step, should it fail next test scripts ?

@winstonliu1111 @ankur-sheth

**Comment by ajbalogh** [comment]
I think it should unless the test effort provides its own cleanup which makes it the test case implementer's explicit responsiblity.
If I was interested in all test cases running regardless of errors then I would provide a cleanup fixture that gets run prior and after each test to ensure state is clean. The blunt force approach of always clearing used to be done with a clear config which increased test time.

**Comment by ajbalogh** [comment]
@pytest.fixture(autouse=True, scope=​'fixture'​)
def stop_traffic(api):
    # stop all traffic here at the end of a test

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
