### ISSUE TITLE
Getting keyError when trying to get flow_stats based on column_name

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#139]
`    flow_results = api.get_flow_results(result.FlowRequest(
                                        flow_names=[],
                                        column_names=['name']))`

FAILED tests/statistics/test_flow_stat_with_flow_name.py::test_port_stat_with_column_name - KeyError: 'port_tx'

**Comment by alakendu** [comment]
Probably this will fix within https://github.com/open-traffic-generator/ixnetwork/pull/136

**Comment by alakendu** [comment]
Not getting this issue after merge of 027756a65563b6998198c46b646592c3b75aa05f
