### ISSUE TITLE
'bytes_tx' always returns 0 though frames are sent

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#142]
[{'name': 'f1', 'transmit': 'stopped', 'port_tx': 'raw_tx', 'port_rx': 'raw_rx',` 'frames_tx': 1000`, 'frames_rx': 1000, 'frames_tx_rate': 0.0, 'frames_rx_rate': 0.0,`'bytes_tx': 0`, 'bytes_rx': 74000, 'loss': 0.0, 'bytes_tx_rate': 0.0, 'bytes_rx_rate': 0.0}]

**Comment by ashutshkumr** [comment]
@ANISH-GOTTAPU kindly check if IxN traffic item / flow stats support displaying `bytes_tx`. If not, we'll probably keep this as no-op.

@alakendu @ajbalogh

**Comment by ANISH-GOTTAPU** [comment]
@ashutshkumr Yes `bytes_tx` is not available in ixN GUI. I would recommend to delete it instead of returning 0

**Comment by ashutshkumr** [comment]
Need to check how we can use capability API to find out `bytes_tx` is not supported.

@ankur-sheth  @winstonliu1111

**Comment by ashutshkumr** [comment]
removed from model
