### ISSUE TITLE
pfc pause frame is created twice

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/ixnetwork#152]
The following config should only create one pfc pause frame not two.
This appears to be collateral.
Will need a test to make sure there is no collateral in the future.

```
    config.flows.append(
        flow.Flow(name='send pause cos3 frames',
                  tx_rx=flow.TxRx(
                      flow.PortTxRx(tx_port_name=rx_port.name,
                                    rx_port_name=tx_port.name)),
                  packet=[
                      flow.Header(
                          flow.PfcPause(
                              src=flow.Pattern('00:AB:BC:AB:BC:AB'),
                              class_enable_vector=flow.Pattern('ffff'),
                              pause_class_0=flow.Pattern('ffff'),
                              pause_class_1=flow.Pattern('ffff'),
                              pause_class_2=flow.Pattern('ffff'),
                              pause_class_3=flow.Pattern('ffff'),
                              pause_class_4=flow.Pattern('ffff'),
                              pause_class_5=flow.Pattern('ffff'),
                              pause_class_6=flow.Pattern('ffff'),
                              pause_class_7=flow.Pattern('ffff')))
                  ],
                  duration=flow.Duration(flow.FixedPackets(packets=1)),
                  size=flow.Size(64),
                  rate=flow.Rate(value=100, unit='line')))

    api.set_state(control.State(config_state))
    api.set_state(control.State(config_state))
```

**Comment by alakendu** [comment]
I am not able to reproduce in latest codebase. I am using this code to test inhouse. Could you please double check and let me know if I have missed something

`from abstract_open_traffic_generator.config import Config
from abstract_open_traffic_generator import (
    flow, control
)

def test_pfc_pause_config(api, tx_port, rx_port):
    """Configure only a pfc pause frame
    """
    config = Config(ports=[tx_port, rx_port])
    config.flows.append(
        flow.Flow(name='send pause cos3 frames',
                  tx_rx=flow.TxRx(
                      flow.PortTxRx(tx_port_name=rx_port.name,
                                    rx_port_name=tx_port.name)),
                  packet=[
                      flow.Header(
                          flow.PfcPause(
                              src=flow.Pattern('00:AB:BC:AB:BC:AB'),
                              class_enable_vector=flow.Pattern('ffff'),
                              pause_class_0=flow.Pattern('ffff'),
                              pause_class_1=flow.Pattern('ffff'),
                              pause_class_2=flow.Pattern('ffff'),
                              pause_class_3=flow.Pattern('ffff'),
                              pause_class_4=flow.Pattern('ffff'),
                              pause_class_5=flow.Pattern('ffff'),
                              pause_class_6=flow.Pattern('ffff'),
                              pause_class_7=flow.Pattern('ffff')))
                  ],
                  duration=flow.Duration(flow.FixedPackets(packets=1)),
                  size=flow.Size(64),
                  rate=flow.Rate(value=100, unit='line')))

    config_state = control.ConfigState(config=config, state='set')
    api.set_state(control.State(config_state))
    api.set_state(control.State(config_state))`

Packet format within IxNetwork 
![image](https://user-images.githubusercontent.com/35574510/101868573-a4787d80-3ba3-11eb-8e69-370779eb4b5c.png)

**Comment by ajbalogh** [comment]
Hi @alakendu - you are correct, I'm also unable to reproduce this. If you would expand the test to include checks that there is only one stack item (not including trailer) and it is pfc as this is an important feature and should be part of the sanity.
