### ISSUE TITLE
All ports are getting configured with same speed on Novus

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#153]
when configuring the speed to 40 or 100 on the novus, all ports in the card are getting configured with 40 or 100 and other user ownership is getting cleared.

same thing tried manually, the vport configuration is applied to physical ports that were assigned to.

**Comment by alakendu** [comment]
This should address in https://github.com/open-traffic-generator/ixnetwork/commit/6efdc9ce5883463113ba3a76624636c2b885e671
