### ISSUE TITLE
If chassis is not reachable in 10 sec, OTG gives exception

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#154]
I was using the chassis which is located in US, and connecting to it is taking time. But OTG is waiting for 10 sec and raising an error.
    
RuntimeError: After 10 seconds, not all location hosts [10.36.87.215] are reachable
    
checked the models to increase the timeout but found none. Will adding timeout is a use case? or do we need to increase the timeout and poll for it?

**Comment by ajbalogh** [comment]
timeout has been increased to 60 seconds which should be sufficient
