### ISSUE TITLE
If physical port speed and config speed is same, do we need to reconfigure it?

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#155]
if the port was set to 100g already by manually or automation. 
OTG is not picking that info and applying the speed on all ports and leading to the issue #153

do we need to reconfigure it?

**Comment by ashutshkumr** [comment]
The problem is, it's still not clear what we should do if the speed is not provided by user.
Picking up a fixed default speed (e.g. 1G) is not an option here. We might need to resort to traffic engine specific default.

This needs more discussion.
@ajbalogh @ankur-sheth @winstonliu1111 @alakendu

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
