### ISSUE TITLE
'NOVUS10/5/2.5/1/100M16DP' LM always defaults to Aggregation mode with "speed_10_gbps"

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#160]
'NOVUS10/5/2.5/1/100M16DP' LM always defaults to 10G Aggregated mode if speed is set to "speed_10_gbps"

From GUI there are two modes as shown
![image](https://user-images.githubusercontent.com/48308607/102049953-e30e7200-3e07-11eb-83e2-81e4c579b7a8.png)

But the restpy return the available modes as ['normal', 'tenGigAggregation'] which are mapped to '10G Non-agg'&'10G agg' respectively

<b>RootCause</b>:
`available_mode` is matched with card available modes and `speed_10_gpbs` is matching with `tenGigAggregation` , so always the card ends up in tenGigAggregation. 

code block ref:
https://github.com/open-traffic-generator/ixnetwork/blob/master/ixnetwork_open_traffic_generator/vport.py#L416

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
