### ISSUE TITLE
EthernetPause doesn't create custom header if no args passed

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#167]
EthernetPause doesn't create custom header if no args or no pause args are passed.

Ex:
f.packet = [
        flow.Header(
            flow.EthernetPause()
        )
    ]

**Comment by alakendu** [comment]
I am not getting this issue in latest code. Could you please double check let me know if I did something wrong
    default_pause = Header(
        EthernetPause())

![image](https://user-images.githubusercontent.com/35574510/102391648-000b9680-3ffc-11eb-91ce-abb16cc3a5a5.png)

**Comment by Rangababu-R** [comment]
yes in the latest, the issue is not seen.

Thanks, Alakendu
