### ISSUE TITLE
Traffic is not resuming on the paused flow

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#168]
Traffic is not resuming on the paused flow with start state. As there is no resume `FlowTransmitState`, I think the start state should resume the flow.

    # start flows
    api.set_state(State(FlowTransmitState(state='start')))

    #pause flow
    api.set_state(State(FlowTransmitState(state='pause')))

    #resume flow
    api.set_state(State(FlowTransmitState(state='start')))

**Comment by alakendu** [comment]
that map with 'resume'

**Comment by ANISH-GOTTAPU** [comment]
But resume state is not available in mode

![image](https://user-images.githubusercontent.com/48308607/102214111-c2c0df00-3efd-11eb-94a2-12a20f189b49.png)

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
