### ISSUE TITLE
IxNet gives warning if pfc_queue configured with list or counter

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#176]
For any flow if pfc_queue is configured with list or counter, IxNetwork gives the below warning.
![image](https://user-images.githubusercontent.com/72373312/102449555-8ce53d00-405a-11eb-8f6c-c6b6e25ac087.png)

Do we need to allow other patterns at OTG as only fixed gets applied?

**Comment by ajbalogh** [comment]
Its a limitation of the ixnetwork implementation not the model, other implementations may not have this problem.
