### ISSUE TITLE
issue in connect call when port number is not default

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#184]
in ixnetwork.py connect method restport is wrongly assigned to _password variable

tests\utils\common.py:509: in apply_config
    api.set_state(control.State(control.ConfigState(config=cfg, state='set')))
ixnetwork_open_traffic_generator\ixnetworkapi.py:108: in set_state
    self._set_config_state(state.config_state)
ixnetwork_open_traffic_generator\ixnetworkapi.py:122: in _set_config_state
    self._connect()
ixnetwork_open_traffic_generator\ixnetworkapi.py:264: in _connect
    platform = TestPlatform(self._address, rest_port=self._password)
..\..\..\desktop\otg\otg\lib\site-packages\ixnetwork_restpy\testplatform\testplatform.py:67: in __init__
    self._connection = Connection(ip_address, rest_port, platform, log_file_name, ignore_env_proxy, verify_cert, trace, script_watch)
..\..\..\desktop\otg\otg\lib\site-packages\ixnetwork_restpy\connection.py:112: in __init__
    self._scheme = self._determine_test_tool_platform(platform)

**Comment by ashutshkumr** [comment]
https://github.com/open-traffic-generator/ixnetwork/pull/185
