### ISSUE TITLE
Header retained in the flow from previous run

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#191]
`test1`: Add tcp header to the flow `f1`

`test2`: Set the config with raw ethernet header for flow `f1`

Expectation: The flow `f1` should have only raw ethernet header but tcp header is retained from `test1`

`test1`: pytest tests/tcp/test_tcp_header_with_fixed.py
`test2`: pytest tests/traffic/test_stats_filter.py

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
