### ISSUE TITLE
RG breakout happens for 100G Novus card with 25G & 10G speed with 100G port locations

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#204]
1) Existing card is with 100G without breakout.
2) Trying to update the speed to 25G or 10G but with same port locations as 100G for `ex: 1;3, 1;4` . Ideally the locations should be `1;17 & 1;18`

Expectation:
Should get an error as port location available

Result:
Getting an error as port location available but `RG breakout is happening at hardware level `

**Comment by alakendu** [comment]
IxNetwork have "resourcePorts" which contains supported ports for that RG and "activePort" for current mode. Therefore we can't figure it out ultimate port number for new mode. Please let me know if we have any attribute from where we can extract that info.
On the other side I feel this is very corner / negative case where customer want to change some speed with incorrect port number.

**Comment by ajbalogh** [comment]
The user of the API should specify location and speed - if the user changes the speed and the location is no longer valid the implementation should raise an error.  The implementation should not adjust the location to match internal resource groups.

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
