### ISSUE TITLE
Capture: overwrite argument doesn't take effect and defaults to False always

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#209]
`overwrite` argument for capture settings is defaults to False

Pointers:
To `overwrite` buffer settings two options should be updated in vport.py, the below checks to be updated if overwrite is True
`trigger['captureTriggerEnable'] = False`
`'captureMode': 'captureContinuousMode'`

sample test:
[test_capture_settings.zip](https://github.com/open-traffic-generator/ixnetwork/files/5779958/test_capture_settings.zip)

**Comment by ANISH-GOTTAPU** [comment]
`overwrite` is working if run without existing config, but if underlying config is present `overwrite` is not taking effect

[capture.zip](https://github.com/open-traffic-generator/ixnetwork/files/5808121/capture.zip)

Run tests in this order
`1) test_capture_filter_settings`
`2)test_capture_overwrite`

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
