### ISSUE TITLE
Capture: Capture choice pcap is not working

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#211]
As per the model the choice can be enum [basic, pcap]. But looks the implementation is missing for pcap.
pcap `The content of this property must be of pcap filter syntax. https://www.tcpdump.org/manpages/pcap-filter.7.html`

```    config.captures.append(
        Capture(name='capture',
                port_names=[tx_port.name],
                choice='dst port 4200',
                ))
    api.set_state(State(ConfigState(config=config, state='set')))```

By providing pcap format, getting the error `AttributeError: 'Capture' object has no attribute 'basic'`

**Comment by ajbalogh** [comment]
The pcap feature is unsupported and should be reported in the capabilities API.
