### ISSUE TITLE
Create Test for ipv4 Device config with traffic and capture test

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#216]
1. Create ipv4 device config on Tx and Rx ports.
2. validate the device configs.
3. Create traffic with ipv4 device names as end points
4. enable traffic
5. run traffic

Validation:
Validate the source and destination, mac and ipv4 addresses with in the captures.

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
