### ISSUE TITLE
Capture: Additional row is added for every BasicFilter added in the capture

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#219]
Adding `3 BasicFilters` results in adding 6 Filters on the IxNetwork Client. For each BasicFilter there is one more filter added, though not in enabled state looks incorrect

Script:
`    src = MacAddressFilter(mac='source',
                           filter='0000faceface',
                           mask='000000000000')
    dst = MacAddressFilter(mac='destination',
                           filter='0000faceface',
                           mask='000000000000')
    custom = CustomFilter(filter='fffefdfcfbfa',
                          mask='000000000000',
                          offset=50)

    config.captures.append(
        Capture(name='capture',
                port_names=[tx_port.name],
                choice=[
                    BasicFilter(src, and_operator=False, not_operator=True),
                    BasicFilter(dst, and_operator=False, not_operator=True),
                    BasicFilter(custom, and_operator=False, not_operator=True)
                ]))`

GUI:
![image (1)](https://user-images.githubusercontent.com/48308607/104021341-9b032500-51e4-11eb-8e14-7bb59d7a63e5.png)

**Comment by alakendu** [comment]
@ajbalogh  It looks like all those entry will add when we ImportConfig only {'xpath': '/vport[1]/capture/filterPallette', 'SA1': '0000faceface', 'SAMask1': '000000000000'}. Could you please take a look if we can improve this in  ImportConfig  side or suggest next step.

**Comment by alakendu** [comment]
According to our discussion we will not address this IxNetwork specific inconsistency as this will not any effect in model perspective.
