### ISSUE TITLE
Apply changes is not handled in IxNet concrete

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#227]
Apply changes will get enabled when a configuration is updated on a started devices in IxNetwork. which needs to be handled in config class in IxNetwork concrete.

![image](https://user-images.githubusercontent.com/72373312/104315895-a6669100-5501-11eb-95a6-bdcd14c63488.png)

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
