### ISSUE TITLE
Is it mandate to pass ethernet and ipv4/v6 stack in flow config when endpoints are device handles

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/ixnetwork#228]
Below is the flow config code with device group handles. the device groups are ipv4 stateful. If ethernet or ipv4 objects are not passed in the packets param, the existing packet structure is being replaced with upper layer packet header passed in the packets param.

ep = flow.TxRx(
        choice=flow.DeviceTxRx(
            tx_device_names=["TxDevice"],
            rx_device_names=["RxDevice"]
        )
    )
flow.Flow(
            name="TxFlow-2",
            tx_rx=ep,
            duration=flow.Duration(
                flow.FixedPackets(
                    packets=packets
                )
            ),
            packet=[
                **flow.Header(flow.Ethernet()),
                flow.Header(flow.Ipv4()),
                flow.Header(flow.Tcp())**
          ]
)

Just passing flow.Tcp() removes the ethernet and ipv4 headers in Concrete. Is this the expected behavior?

Concrete shall append the headers, anything that fall above the default device group headers.

**Comment by ajbalogh** [comment]
Regardless of the flow.tx_rx endpoint the flow.packet determines the what will be seen on the wire. 
If flow.packet is empty then at this point the model and concrete implementation have defaulted to whatever the traffic generator decides.
The model will be updated to reflect that flow.packet must raise an exception if the implementation cannot create the configured flow.packet.
In that case if the flow.packet is empty and the imp cannot create an empty packet an exception will be raised.
In this case if flow.packet is just tcp and the packet generator cannot create it an exception should be raised.

**Comment by Rangababu-R** [comment]
@ajbalogh 
We had discussed within the team and reached to the below conclusion. As there are some unpredictable assumptions an implementer has to face in concrete.

For Raw traffic: If flow.packet is empty concrete shall default to ethernet header. (only this will be addressed)
For device traffic: if flow.packet is empty will leave with the current behavior which will default to the device packet config of Tgen.

If flow.packet has unordered headers:
Raw traffic: will leave with current implementation.
Device traffic: Here we had discussed the ways how could be addressed but we end up the implementation which would require assuming the header stack and can lead to a complex coding with larger header stack.

So, As the Snappi has dot notation style and this issue would not be seen in it.

**Comment by ashutshkumr** [comment]
FYI, unordered headers can be assigned in snappi too.
```python
config.flows[0].packet.tcp().ethernet()
```

But, either way, implementations shouldn't have any heuristics for validating order of headers, because:
- it's not feasible to cover all possible use cases
- it restricts users from experimenting with non-standard header sequence

To summarize:
- if flow.packet is `[]` or `null`, intended header sequence will be configured based on `txrx device` (e.g. `.ethernet().ipv4()` for ipv4 device) and raw ethernet header will be configured for `txrx port`
- otherwise, the exact header sequence will be configured (e.g. ethernet won't be automatically prepended here: `.ipv4().tcp()`)

@ankur-sheth @winstonliu1111

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
