### ISSUE TITLE
Flow framesize is being ignored

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/ixnetwork#235]
User configures multiple flows on a single port one of which contains only a pfcpause packet header with a framesize of 64 bytes.
The flow that contains the pfcpause packet header has its framesize adjusted to a larger size.

The configuration should be immutable (ie if the user asks for 64 byte framesize it should provide that or return an error indicating it is unable to do that).

This issue is being seen with the following test when being run against mellanox 2700:
https://github.com/Azure/sonic-mgmt/blob/master/tests/pfc/test_pfc_pause_lossy.py

**Comment by ashutshkumr** [comment]
https://github.com/open-traffic-generator/ixnetwork/releases/tag/v0.0.73
