### ISSUE TITLE
Snappi: Need flow endpoints to be routerange names

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#249]
rx1_rr = rx1_device.bgpv4.bgpv4_route_ranges.bgpv4routerange()[-1]
    rx1_rr.name = "rx1_rr"

    rx2_rr = rx2_device.bgpv4.bgpv4_route_ranges.bgpv4routerange()[-1]
    rx2_rr.name = "rx2_rr"

    flow.tx_rx.device.rx_names = [rx1_rr.name, rx2_rr.name]

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
