### ISSUE TITLE
Traffic apply error if endpoints are updated from device to ports

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#261]
1) Test1(test_ip_device_and_flow.py) has endpoints as devices
2) Test2(test_flow_rate.py) has endpoints as ports.

If Test1 and Test2 are run consecutively, will get the below error

`Unable to create endpoint sets. Verify the endpoints are valid.`

Attaching two tests for issue reproduction

[test_ip_device_and_flow.zip](https://github.com/open-traffic-generator/ixnetwork/files/5941981/test_ip_device_and_flow.zip)

**Comment by alakendu** [comment]
At the time of debugging in IxNetwork it looks like similar issue fix within IxNetwork-9.10Update1 (BUG1547380: Unable to create traffic item after destroying topology).
I am not getting this issue in IxNetwork-9.10 Update1. Could you please validate it.

**Comment by ashutshkumr** [comment]
@ANISH-GOTTAPU please check this in IxN 9.10 update 1
