### ISSUE TITLE
can not create traffic flows with ethernet endpoints

### ISSUE THREAD

**Issue by dgalan-xxia** [open-traffic-generator/ixnetwork#267]
I have devices configured with IPv4
I want to create traffic flows using the Ethernet stacks as endpoints.

            # Create TGen device
            device_name = TgenUtil.create_tgen_device_name_from_sr_port(host.front_panel_port)
            device = tgen_device.Device(name=device_name,
                            container_name=TgenUtil.create_tgen_port_name_from_sr_port(host.front_panel_port),
                            device_count=1,
                            choice=tgen_device.Ipv4(name=f'IPv4{host.front_panel_port}',
                                        address=tgen_device.Pattern(host.address),
                                        prefix=tgen_device.Pattern('32'),
                                        gateway=tgen_device.Pattern(gateway),
                                        ethernet=tgen_device.Ethernet(name=f'Eth{host.front_panel_port}')))
            devices.append(device)
            device_names.append(device.name)
            ethernet.append(f'Eth{host.front_panel_port}')

        # 2. Create full mesh of flows
        endpoint = DeviceTxRx(tx_device_names=ethernet,
                                        rx_device_names=ethernet)
        flow = Flow(name='Full Mesh Traffic',
                    tx_rx=TxRx(endpoint),
                    packet=[
                        Header(Ethernet()),
                        Header(Ipv4()),
                        Header(Udp(
                            src_port=Pattern(Counter(start='80', step='1', count=1000000)),
                            dst_port=Pattern(Counter(start='80', step='1', count=1000000))))
                    ],
                    size=Size(frame_size),
                    rate=Rate(unit='line', value=line_rate),
                    duration=Duration(FixedPackets(packets=packet_count)))

![image](https://user-images.githubusercontent.com/26799136/107274558-6a8df100-6a05-11eb-8029-4ee993015b85.png)

This fails with:  **AttributeError: 'Ethernet' object has no attribute 'choice'**  

    def set_state(self, state):
        """Abstract API implementation
        """
        if isinstance(state, (State, str, dict, type(None))) is False:
            raise TypeError(
                'The content must be of type (Config, str, dict, type(None))' %
                Config.__class__)
        if isinstance(state, str) is True:
            state = self._dict_to_obj(json.loads(state))
        elif isinstance(state, dict) is True:
            state = self._dict_to_obj(state)
        if state.choice == 'config_state':
>           self._set_config_state(state.config_state)
 
..\..\Envs\shrinkray-api-server\lib\site-packages\ixnetwork_open_traffic_generator\ixnetworkapi.py:109:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 
self = <ixnetwork_open_traffic_generator.ixnetworkapi.IxNetworkApi object at 0x00000240D9AB3190>
config_state = <abstract_open_traffic_generator.control.ConfigState object at 0x00000240D9C74310>
 
    def _set_config_state(self, config_state):
        """Set or update the configuration
        """
        self._config = config_state.config
        self._config_objects = {}
        self._ixn_objects = {}
        self._capture_request = None
        self._errors = []
        self._connect()
        with Timer(self, 'Config validation'):
            self.validation.validate_config()
        if self._config is None:
            self._ixnetwork.NewConfig()
        else:
            self.vport.config()
            with Timer(self, 'Devices configuration'):
               self.ngpf.config()
            with Timer(self, 'Flows configuration'):
>               self.traffic_item.config()
 
..\..\Envs\shrinkray-api-server\lib\site-packages\ixnetwork_open_traffic_generator\ixnetworkapi.py:133:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 
self = <ixnetwork_open_traffic_generator.trafficitem.TrafficItem object at 0x00000240D9AB32B0>
 
    def config(self):
        """Configure config.flows onto Ixnetwork.Traffic.TrafficItem
 
        CRUD
        ----
        - DELETE any TrafficItem.Name that does not exist in config.flows
        - CREATE TrafficItem for any config.flows[*].name that does not exist
        - UPDATE TrafficItem for any config.flows[*].name that exists
        """
        ixn_traffic_item = self._api._traffic_item
        self._api._remove(ixn_traffic_item, self._api.config.flows)
        if self._api.config.flows is not None:
            for flow in self._api.config.flows:
                args = {
                    'Name': flow.name,
                    'TrafficItemType': 'l2L3',
>                   'TrafficType': self._get_traffic_type(flow),
                    'SrcDestMesh': 'oneToOne' if flow.tx_rx.choice == 'port' else 'manyToMany'
                }
 
..\..\Envs\shrinkray-api-server\lib\site-packages\ixnetwork_open_traffic_generator\trafficitem.py:154:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 
self = <ixnetwork_open_traffic_generator.trafficitem.TrafficItem object at 0x00000240D9AB32B0>
flow = <abstract_open_traffic_generator.flow.Flow object at 0x00000240D9C8FB50>
 
    def _get_traffic_type(self, flow):
        if flow.tx_rx is None:
            raise ValueError('%s Flow.tx_rx property cannot be None' %
                             flow.name)
        elif flow.tx_rx.choice == 'port':
            encap = 'raw'
        else:
            encap = None
            for name in flow.tx_rx.device.tx_device_names:
                **device = self._api.get_config_object(name)
>               if device.choice == 'ethernet':
E               AttributeError: 'Ethernet' object has no attribute 'choice'
 
..\..\Envs\shrinkray-api-server\lib\site-packages\ixnetwork_open_traffic_generator\trafficitem.py:201: AttributeError**

**Comment by ashutshkumr** [comment]
fixed per `snappi[ixnetwork]==0.3.12`
