### ISSUE TITLE
Traffic statistics are all zero except for the first traffic item

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/ixnetwork#297]
customer: Wei @msft
ixn 9.10.2007.146
tgen 0.0.73

Steps to reproduce:
set config of test.json
start transmit 

Problem:
after 20 seconds get results still returns all flows with zero values for tx, rx metrics

Notes:
After the test run is stopped, leave the ixn session up and the UI confirms the flow statistics counters are all zero.
Start traffic again, generate is done and flow statistics now show correct values.

**Comment by ajbalogh** [comment]
[test.zip](https://github.com/open-traffic-generator/ixnetwork/files/6039855/test.zip)

**Comment by Rangababu-R** [comment]
@ajbalogh is the issue seen in standalone or in regression?

**Comment by Rangababu-R** [comment]
@ajbalogh @ashutshkumr 
given some temporary work around for now. need more time to analyze the issue in our local.
https://github.com/open-traffic-generator/ixnetwork/commit/44ea44fc4b03245815cda3c9e47ed2b34034e167
please review the above commit

**Comment by ajbalogh** [comment]
@Rangababu-R  the issue seen by Wei was standalone and not part of any regression. It was reproducible every time using the ixnetwork container.

**Comment by ajbalogh** [comment]
The latest change did not resolve the problem.
During a debugging session we added code to wait (for 60 seconds) in between protocols up and traffic generate/apply - this did not work. We then tried regenerate/apply twice before starting traffic - this did not work.
The only thing that works is to start traffic, stop traffic and start traffic again - only then do the traffic item flow statistics accurately report tx/rx frames and stop after sending all frames.

**Comment by Rangababu-R** [comment]
Andy could ask Wei to share the screen shots of the below.
1. traffic items before traffic start first time.
2. errors/warning window before and after the traffic start first time.
3. traffic items after the first time start and stop.
it will help analyze the issue accurately.

**Comment by Rangababu-R** [comment]
@ajbalogh, @ashutshkumr 
able to reproduce the issue with Wei's config and provided the fix in below commit
https://github.com/open-traffic-generator/ixnetwork/commit/cac5c0ad9be824a97be4d175c505aa424d2d5253

**Comment by Rangababu-R** [comment]
@ajbalogh.
able to reproduce the issue with Wei's config.
Issue is with the flow names. in Wei's configuration the flow names has special characters "(", which is failing to fetch the traffic items when finding with Name. fixed the issue in below PR. please review it.
it shall work this time.
https://github.com/open-traffic-generator/ixnetwork/pull/300

**Comment by ajbalogh** [comment]
@Rangababu-R the fix for traffic start worked but Wei's test was still failing when attempting to get results for specific flow names. It appears those flow names are not escaped.  

The workaround in Wei's test was to change the names so that no special characters were present but we should ensure that anything used in a restpy find() method is properly escaped.

Once the fix is in Wei will retest using the new version and the original flow names with special characters.

**Comment by Rangababu-R** [comment]
@ajbalogh issue with flow stats is fixed.

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
