### ISSUE TITLE
Ports are not getting connected while running snappi on linux api server

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/ixnetwork#298]
Ran the script  https://github.com/open-traffic-generator/snappi-tests/blob/master/tests/convergence/bgp_convergence_config.py
 in Linux api server getting the below error message

        except:
            pass
        # raise the appropriate error
        message = '\n'.join(errors)
        if response.status_code == 400:
>           raise BadRequestError(message, response.status_code)
E           ixnetwork_restpy.errors.BadRequestError:  port 10.36.78.53;09;06 is not available
E           port 10.36.78.53;09;07 is not available
E           port 10.36.78.53;09;08 is not available

/usr/lib/python3.9/site-packages/ixnetwork_restpy/connection.py:350: BadRequestError

FAILED test_get_DPDP_Convergence.py::test_bgp_dp_dp_convergence - ixnetwork_restpy.errors.BadRequestError:  port 10.36.78.53;09;06 is not available

**Comment by ANISH-GOTTAPU** [comment]
some issue with the card, works fine after card hotswap..
