### ISSUE TITLE
( test script) Move Port/Device/IP configuration from test script to comon fixture

### ISSUE THREAD

**Issue by SubhajitPalKeysight** [open-traffic-generator/ixnetwork#30]
Move al common coding like Port/Device/IP etc on fixture . Otherwise we may not get good feedback from user. Wrap this into a fixture. 

>Explore not to import all lases individually  in test script.

>Use similar like fixture 

def b2b_ipv4_device_groups(tx_port, rx_port):
    """Returns a B2B tuple of tx devices to rx devices
    Protocol stack is eth + vlan + ipv4
    Number of devices is 1
    """

**Comment by ashutshkumr** [comment]
This repository now only holds unit tests where config in most tests are provided as a fixture.
