### ISSUE TITLE
Smart Apply error for batch run

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#310]
If multiple tests are run in batch, getting the below error

E           ixnetwork_restpy.errors.BadRequestError: Connected To: Changing the element in a started element is not permitted.
E               Current Server Errors/Warnings:
E               03/10/2021 12:27:29 [ERROR] 
E               03/10/2021 12:26:58 [WARNING] The frame size was increased to 66 bytes to accommodate encapsulation requirements.  - The frame size was adjusted to conform to the encapsulation requirements

Script:
[test_bgp_policies.zip](https://github.com/open-traffic-generator/ixnetwork/files/6113949/test_bgp_policies.zip)

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
