### ISSUE TITLE
flow_stat[index] are not referenceing to the proper rows

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/ixnetwork#318]
say if there are multiple flows in flow stats

flow_stats = get_flow_stats(snappi_api)
On printing flow_stats[0].loss,flow_stats[1].loss ,flow_stats[2].loss and so on ....

they are not printing the correct loss% values for the respective row index that we are seeing in the GUI which is a major bug that needs fixing.

The indexing is jumbled up as we scale up the number of flows

**Comment by ANISH-GOTTAPU** [comment]
@selldinesh : As discussed, we don't have control on the stats mapping to row index from GUI. use any reference value like `flow_names` or `port_rx` and get the stats
