### ISSUE TITLE
BGP session state is not being reported properly

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/ixnetwork#319]
1. BGP sessions total and sessions up are shown as zero even if the states are up
2. If there are 3 BGP sessions  len(results.bgpv4_metrics) returns value more than 3 and sometimes zero

Below is the code snippet  for which the asser statements are failing

req = snappi_api.metrics_request()
req.bgpv4.column_names = ['sessions_total', 'sessions_up']
results = snappi_api.get_metrics(req)
assert len(results.bgpv4_metrics) == 3
for i in range(0,3):
    assert results.bgpv4_metrics[i].sessions_total == 1
    assert results.bgpv4_metrics[i].sessions_up == 1

**Comment by ANISH-GOTTAPU** [comment]
As discussed, please re-open the issue if reproduced again
