### ISSUE TITLE
BGP SRTE: Enable IPv4 SR & IPv6 SR TE Policy capabilities  if SRTE is enabled

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#340]
BGP SRTE: Enable IPv4 SR & IPv6 SR TE Policy capabilities

![image](https://user-images.githubusercontent.com/48308607/114396783-94a59000-9bbb-11eb-883e-90d5b28d70e7.png)

**Comment by alakendu** [comment]
Fix in https://github.com/open-traffic-generator/ixnetwork/commit/4ba555ba19c24c64cb9d6ddd9adbd11bd64b2095

**Comment by ANISH-GOTTAPU** [comment]
fixed and verified with https://github.com/open-traffic-generator/ixnetwork/pull/360
