### ISSUE TITLE
BGP SRTE: as per RFC each SR policy should have only one tunnel tlv, should we still go with DeviceBgpTunnelTlvIter?

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#349]
As per RFC each SR policy should have only one tunnel tlv as shown, when checked with Anirban he updated me that the option is enabled for negative testing.

![image](https://user-images.githubusercontent.com/48308607/114877825-4b547b00-9e1d-11eb-9d15-2ae021a5916a.png)

https://tools.ietf.org/pdf/draft-ietf-idr-segment-routing-te-policy-05.pdf

**Comment by ANISH-GOTTAPU** [comment]
@apratimmukherjee @ajbalogh , any comments on this?

**Comment by anirbanb07** [comment]
Hi Anish, as discussed in our meeting earlier this week, IxNetwork support more than tunnel-TLVs to let user do negative configuration. More than one TLV is not expected as per standard. Whether we should have it here depends on whether we intend to provide negative conformance test capacity through these APIs. If the answer is no, then we don't need to support multiple tunnel TLVs.

**Comment by ajbalogh** [comment]
The model currently allows for 0..n tunnel tlv.  The description can be extended to indicate the RFC standard allows for only one tunnel tlv and additional information regarding negative testing using additional tunnel tlvs can be added. 

Changing the model to allow only a single tunnel tlv means not providing negative test capability in the future without adding model complexity (another node for 0..n relationships).

The use case that is driving this model only has a single tunnel tlv.  

@greg-dennis it would be interesting to hear your opinion on this issue, do you anticipate any negative protocol test scenarios?

**Comment by ashutshkumr** [comment]
Per discussion, we'll keep it as is.
