### ISSUE TITLE
BGP SRTE: few fields retained default values instead of user defined values

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#350]
Below are the fields retaining default values
1) policy_type
2) next_hop_mode
3) next_hop_address_type

p1.policy_type = p1.IPV6
hop.next_hop_mode = hop.MANUAL
hop.next_hop_address_type = hop.IPV6

<b>Pointer</b>:  imports is not working as expected for dropdown/enums in  GUI

![image](https://user-images.githubusercontent.com/48308607/115150944-4b0be800-a088-11eb-95ae-5e39be829ed1.png)

**Comment by alakendu** [comment]
Multivalue Enum fix is available in >= IxNetwork-9.10 Update1 . Issue will not reproduce if we will move to that version. 
Please let me know if that is fine. Otherwise we need to use other pattern to address this issue.

**Comment by ANISH-GOTTAPU** [comment]
issue not seen with 9.10 update1
