### ISSUE TITLE
BGP SRTE: SRTE policy on bgpv4 is throwing attribute error

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#351]
SRTE policy on bgpv4 is throwing attribute error

re.search always returns None for bgpv4 and trying to apply SRTE on bpgv6 which is not available.

<b> pointer </b>:
(Pdb) ixn_bgp.href
'/api/v1/sessions/1/ixnetwork/topology/1/deviceGroup/1/ethernet/1/ipv4/1/bgpIpv4Peer/1'
(Pdb) print(re.search(ixn_bgp.href, 'bgpIpv4Peer'))
None
` If I update the search strings in below format it works`
(Pdb) print(re.search('bgpIpv4Peer', ixn_bgp.href))
<re.Match object; span=(72, 83), match='bgpIpv4Peer'>

**Comment by alakendu** [comment]
fix in https://github.com/open-traffic-generator/ixnetwork/commit/2dd1171a948388eeeda3a48145a3be20b2ee482c

**Comment by ANISH-GOTTAPU** [comment]
fixed with https://github.com/open-traffic-generator/ixnetwork/pull/360
