### ISSUE TITLE
Experiencing an intermittent error when running a sonic test

### ISSUE THREAD

**Issue by alakendu** [open-traffic-generator/ixnetwork#356]
![exception](https://user-images.githubusercontent.com/35574510/115694799-d46c3480-a37e-11eb-9b42-8ab85c888371.png)

[Andy]
I noticed that the stack trace executes PauseStatelessTraffic.
I'm able to reproduce this using PauseStatelessTraffic using the rest api.
I start traffic on a configuration then stop it.
I then use a rest client to execute the pauseStatelessTraffic and it gives me that exact error.

**Comment by ANISH-GOTTAPU** [comment]
issue verified with `ixnetwork-open-traffic-generator==0.0.79`
