### ISSUE TITLE
abstract: Auto Negotation is not applied properly with Python 2.7 

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#376]
If user is sending 2 ports with Auto Negotation disabled, Auto Neg gets applied only on Port1 and not applied on Port2

(Pdb) pp imports
[{'enableAutoNegotiation': False,
  'enableRsFec': False,
  'ieeeL1Defaults': False,
  'linkTraining': False,
  'xpath': u'/vport[1]/l1Config/novusHundredGigLan'},
 {'enableAutoNegotiation': False,
  'enableRsFec': False,
  'ieeeL1Defaults': False,
  'linkTraining': False,
  'xpath': u'/vport[2]/l1Config/novusHundredGigLan'}]

Since IeedL1Defaults need to be applied first, if the dictionary is sent using Python3.8 the server applies ieeeL1Defaults first but in Pthon2.7 the server applies AutoNegotation first which is causing the issue.

2.7
{
  "Arg1": "/api/v1/sessions/20/ixnetwork/resourceManager",
  "Arg2": "[{\"xpath\": \"/vport[1]/l1Config/novusHundredGigLan\", \"enableAutoNegotiation\": false, \"linkTraining\": false, \"enableRsFec\": false, \"ieeeL1Defaults\": false}, {\"xpath\": \"/vport[2]/l1Config/novusHundredGigLan\", \"enableAutoNegotiation\": false, \"linkTraining\": false, \"enableRsFec\": false, \"ieeeL1Defaults\": false}]",
  "Arg3": false
}

3.8
{
  "Arg1": "/api/v1/sessions/21/ixnetwork/resourceManager",
  "Arg2": "[{\"xpath\": \"/vport[1]/l1Config/novusHundredGigLan\", \"ieeeL1Defaults\": false, \"enableAutoNegotiation\": false, \"enableRsFec\": false, \"linkTraining\": false}, {\"xpath\": \"/vport[2]/l1Config/novusHundredGigLan\", \"ieeeL1Defaults\": false, \"enableAutoNegotiation\": false, \"enableRsFec\": false, \"linkTraining\": false}]",
  "Arg3": false
}

script:
[test_layer1.zip](https://github.com/open-traffic-generator/ixnetwork/files/6584250/test_layer1.zip)

**Comment by ajbalogh** [comment]
This should be raised as a BUG with the portmanager team as there is no concept of order in sdm.  The portmanager publisher/handler that sets the sdm attributes should receive all attributes regardless of order then apply them in the correct order.

**Comment by ANISH-GOTTAPU** [comment]
verified with 0.0.82
