### ISSUE TITLE
SONiC : ECN Test Scripting 

### ISSUE THREAD

**Issue by SubhajitPalKeysight** [open-traffic-generator/ixnetwork#41]
Develop Configuration of ECN Test

Check if we can have egress tracking for stat ( check from Kamal )

Later we will integrate capture.

**Comment by ashutshkumr** [comment]
@ajbalogh is it ok to rename it to ECN and move to `stabilize` ?

**Comment by ajbalogh** [comment]
Yes please - thanks!

**Comment by ashutshkumr** [comment]
The unit tests covers all PFC TCs that can be validated against B2B ports. ECN, PFCWD and PFC TCs written in snappi have been contributed to SONiC mgmt repository.
