### ISSUE TITLE
IP Priority TOS support 

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#44]
Need support to update TOS values from 0-7 

As of now, DSCP supports values 0, 8, and above. As per the sonic test case, have to update the TOS value from 0 to 7 

Sonic Test cases:
===========
On SONiC DUT configure the following:

Enable watchdog with default storm detection time (400ms) and restoration time (2sec).
Configure a single lossless priority value Pi (0 <= i <= 7).
To minimize configuration complexity, it is recommended that the SONiC DUT be configured as either Top of Rack (ToR) or Tier 0 (T0) switch with three VLAN interfaces.
Configure following traffic items on the Keysight device:

Traffic 1<->2 : Bi-directional traffic between Keysight port 1 and port 2, with DSCP value mapped to lossless priority Pi configured in the DUT. Traffic Tx rate should be configured as 50% of line rate.
Traffic 2<->3 : Bi-directional traffic between Keysight port 2 and port 3, with DSCP value mapped to lossless priority Pi configured in the DUT. Traffic Tx rate should be configured as 50% of line rate.
PFC pause storm: Persistent PFC pause frames from Keysight port 3 to et3 of DUT. Priority of the PFC pause frames should be same as that configured in DUT and the inter-frame transmission interval should be lesser than per-frame pause duration.

**Comment by ajbalogh** [comment]
This has been modeled and needs to be implemented.
