### ISSUE TITLE
All stats are returning 0, even if stats are available in GUI

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#49]
{'columns': ['name',
             'state',
             'port_tx',
             'port_rx',
             'frames_tx',
             'frames_rx',
             'frames_tx_rate',
             'frames_rx_rate',
             'bytes_tx_rate',
             'bytes_rx_rate',
             'loss'],
 'rows': dict_values([['Traffic 1<->2', 'stopped', 'Port1', 'Port2', 0, 0, 0, 0, 0, 0, 0]])}

I assume "table.AddRowFilter('Traffic Item', StatViewAssistant.REGEX, filter['regex'])" line in trafficitem.py is causing the error and coming out of the try block

**Comment by abhijit-dhar** [comment]
I also got this issue, earlier it was not there. 
        ```
        api.set_config(base_config)

        # start all flows
        api.set_flow_transmit(FlowTransmit(state='start'))

        exp_dur = start_delay + traffic_duration
        logger.info("Traffic is running for %s seconds" %(exp_dur))
        time.sleep(exp_dur)

        # stop all flows
        api.set_flow_transmit(FlowTransmit(state='stop'))

        # Get statistics
        test_stat = api.get_flow_results(FlowRequest())
        logger.info(test_stat)

```
