### ISSUE TITLE
Getting traffic apply error : starting 3rd traffic item(Note:- already 2 traffic items are in run state)

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#50]
As per the test case, I have to start 3rd traffic item after traffic item 1&2 run for some time, but getting traffic apply error
Please find the test case steps 

TestCase:
1) At time TstartTraffic , start all the bi-directional lossless traffic items.
2) At time TstartPause , start PFC pause storm.

**Comment by ajbalogh** [comment]
Need some more information - at a minimum test case location, exception call stack.
A reproducible smaller standalone test case outside of the sonic infrastructure would be the best

**Comment by ANISH-GOTTAPU** [comment]
Test steps
1) Create 3 flows
2) Start 2 flows and start 3rd flow after some time without stopping the other two.

[traffic_apply_error.zip](https://github.com/open-traffic-generator/ixnetwork/files/5287802/traffic_apply_error.zip)


    api.set_flow_transmit(FlowTransmit(state='start',flow_names=['Traffic 1->2','Traffic 2->1']))

    # Wait for sometime, then start pause storm without stopping the other flows
    import time
    time.sleep(3)

    api.set_flow_transmit(FlowTransmit(state='start', flow_names=['Pause Storm']))

Please use the test file attached created with b2b setup, running the test file would reproduce the issue

**Comment by alakendu** [comment]
Add some observation if that will help. Test configure with three flows. First start Two flows then wait for 3sec. Finally trying to start final flow where as global traffic is in running state. Therefore getting internal error when try to execute:
**self._api._traffic.Apply()**
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.2\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\MY_FOLDER\Sonic\Codebase\python\lib\site-packages\ixnetwork_restpy\testplatform\sessions\ixnetwork\traffic\traffic.py", line 840, in Apply
    return self._execute('apply', payload=payload, response_object=None)
  File "C:\MY_FOLDER\Sonic\Codebase\python\lib\site-packages\ixnetwork_restpy\base.py", line 302, in _execute
    response = self._connection._execute(url, payload)
  File "C:\MY_FOLDER\Sonic\Codebase\python\lib\site-packages\ixnetwork_restpy\connection.py", line 210, in _execute
    return self._send_recv('POST', url, payload)
  File "C:\MY_FOLDER\Sonic\Codebase\python\lib\site-packages\ixnetwork_restpy\connection.py", line 426, in _send_recv
    return self._process_response_status_code(url, headers, response, async_status=True)
  File "C:\MY_FOLDER\Sonic\Codebase\python\lib\site-packages\ixnetwork_restpy\connection.py", line 349, in _process_response_status_code
    raise BadRequestError(message, response.status_code)
ixnetwork_restpy.errors.BadRequestError:  Error in L2/L3 Traffic Apply
	Current Server Errors/Warnings:
	09/28/2020 20:18:22 [ERROR] An error occurred while configuring Flow Detective! Please check the logs for more details!
	09/28/2020 20:17:49 [WARNING] Ignore Version Registry Key is Enabled.

**IxNetwork log snippet:**
09/28/2020 20:19:14: TaskRunner: Done  executing 'Generating Traffic' in 00:00:00.0079959
09/28/2020 20:19:14: Traffic: TSM_TRACE - MoveStateMachine - Description: Generating
09/28/2020 20:19:14: 
09/28/2020 20:19:14: Traffic: IxNetwork.Middleware.TrafficModule: Unable to move to State kUnapplied; Current State is : Started(8)
09/28/2020 20:19:14: Traffic: Calling Generate(multiple TIs) - END

I am thinking if we add validation for global flow state (self._api._traffic.State) if that will help.

**Comment by ANISH-GOTTAPU** [comment]
Yes, can we add a flag like "apply_traffic", make it true as default and use can pass False if don't want to apply traffic and just send. Not sure how much it can blend with openAPI, just asking

**Comment by ajbalogh** [comment]
this test case demonstrates staggered flow start https://github.com/open-traffic-generator/ixnetwork/blob/master/tests/test_staggered_flow_start.py
