### ISSUE TITLE
All the stats(rows values) are returned in string format, can we return as float

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#53]
All stats(rows values) are returning in string format currently, so it is overhead in the script every time to add float(tx_frames) 

{'columns': ['name',
             'state',
             'port_tx',
             'port_rx',
             'frames_tx',
             'frames_rx',
             'frames_tx_rate',
             'frames_rx_rate',
             'bytes_tx_rate',
             'bytes_rx_rate',
             'loss'],
 ['Traffic 3->2',
 'started',
 'Port3',
 'Port2',
 '708550904',
 '136428955',
 '5986590.000',
 '0.000',
 '6130268160.000',
 '0.000',
 '80.745']

**Comment by ajbalogh** [comment]
The model for Result.Table is indeterminate so everything must be a string https://github.com/open-traffic-generator/models/blob/master/result/result.yaml
