### ISSUE TITLE
Model LAG in Open-traffic-generator

### ISSUE THREAD

**Issue by SubhajitPalKeysight** [open-traffic-generator/ixnetwork#54]
Model Lag .
Lag acts as logical port  ( LAG is a logical port under which there will be physical ports ) 
Protocol like IP , BGP etc to be configured over LAG port
Traffic over LAG

**Comment by ajbalogh** [comment]
initial concept - many port objects can participate in a lag and each participating port cannot have any of its own device configuration - @SubhajitPalKeysight  what do you think?

![image](https://user-images.githubusercontent.com/30300566/95270923-76686d00-07f1-11eb-8b39-5544a668ffd1.png)

**Comment by ajbalogh** [comment]
modeled in this PR https://github.com/open-traffic-generator/models/pull/64
