### ISSUE TITLE
Getting "Could not convert string to float" error if stats are taken when traffic is in started state

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#57]
I could see sometimes Loss is shown as * in the GUI and returns string ' ' as shared in Snapshot. During this time if I am trying to pull the stats I am getting an error

(Pdb) test_stat = api.get_flow_results(FlowRequest(flow_names=['Traffic 1->2']))
*** Exception: could not convert string to float: ''

![traffic](https://user-images.githubusercontent.com/48308607/95311009-b0e21080-08aa-11eb-9c78-567eecffb2a4.JPG)

**Comment by ajbalogh** [comment]
resolved with https://github.com/open-traffic-generator/ixnetwork/commit/2138414be9de51758a121d58b5b1f82905478992
abstract-open-traffic-generator 0.0.61
ixnetwork-open-traffic-generator 0.0.23
