### ISSUE TITLE
Test coverage needed for layer1

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/ixnetwork#67]
Pytest coverage is needed for different chassis types, card types and port speeds.
Some examples being used are ares, optixia xm2, novus, uhd, speed_40_gbps, speed_100_gbps, speed_10_gbps.
The test should verify that given a config with a port location and layer1 speed the library MUST automatically adjust card resource group mode.

**Comment by ashutshkumr** [comment]
Covered for Novus 5 speed, Novus100G, AresONE400 and UHD.
