### ISSUE TITLE
Some attributes in port and flow results are arbitarily missing

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/ixnetwork#72]
Upon running unidirectional b2b test with one flow, it's seen that not all `columns` are returned for port and flow stats.

```sh
# port stats - tx
{'name': 'tx', 'location': '10.74.44.174;1;1;connected', 'link': 'up', 'capture': 'stopped', 'frames_tx': 0, 'frames_rx': 0, 'frames_tx_rate': 0, 'frames_rx_rate': 0, 'bytes_tx': 0, 'bytes_rx': 0, 'bytes_tx_rate': 0, 'bytes_rx_rate': 0}

# port stats - rx - most stats missing compared to tx
{'name': 'rx', 'location': '10.74.44.174;1;2;connected', 'link': 'up', 'capture': 'stopped'}

# flow stats - bytes_rx count is missing
{'name': 'raw tx->rx', 'transmit': 'started', 'port_tx': 'tx', 'port_rx': 'rx', 'frames_tx': 1000, 'frames_rx': 1000, 'frames_tx_rate': 0.0, 'frames_rx_rate': 0.0, 'bytes_tx_rate': 0.0, 'bytes_rx_rate': 0.0, 'loss': 0.0}
```

Another note here: `location` returns the location concatenated with string `connected` even though the original location string shouldn't have been modified.

**Comment by alakendu** [comment]
Please attached/ specify location of that script

**Comment by ashutshkumr** [comment]
This script fetches port and flow stats. You'll see the issue upon dumping them: https://github.com/open-traffic-generator/tests/blob/master/samples/test_raw_eth.py (steps on how to run are in readme.md)

BTW, most of the new issues are now being tracked as part of this project board and the assignee will be decided upon further discussion: https://github.com/open-traffic-generator/ixnetwork/projects/2

**Comment by ashutshkumr** [comment]
There were two issues:
- For flow stats, bytes_rx was not being fetched (instead byte rate stats were being fetched)
- For port stats, exception was raised everytime PFC stats were being extracted for first port, even when those weren't visible in stat view. It never got a chance to proceed to next ports.

Fixed in https://github.com/open-traffic-generator/ixnetwork/commit/d2de08ec36cffd1a229a17dc3d1379d0a754127f
