### ISSUE TITLE
Setting intended speed as part of layer1 config is not reflected on target ports

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/ixnetwork#73]
To reproduce this against VMOne ports, run following from stabilize branch: https://github.com/open-traffic-generator/ixnetwork/blob/stabilize/tests/ethernet/test_fixed_mac_addrs.py

In order to change speed, modify `speed` option in tests/settings.json (from 1G to 100MB FD). The modified speed is not reflected after running the tests.

**Comment by alakendu** [comment]
This issue we are addressing VM port speed. We will prioritize according to the customer require ports and speed.
