### ISSUE TITLE
Retreiving correct pcap requires sending capture request twice

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/ixnetwork#75]
Sending a capture request automatically stops the capture and returns a binary file in .pcap format. But in the first try, it always returns a .pcap file with 0 packets.

Upon second try (without adding any wait) correct .pcap file is returned (with intended packet count).

**Comment by alakendu** [comment]
I am not getting this issue when run this test script ..\ixnetwork\tests\test_capture_pcap.py in my system.
Could you please specify test script, chassis card and port and python version where you able to reproduced it.

**Comment by ashutshkumr** [comment]
In the same script, if you increase the packet count from 100 to 1000, the issue will reproduce.

**Comment by alakendu** [comment]
Internally setting max time_out to 90sec with 3sec polling interval. But this limit will may overshoot for some corner case. Please think if we can expose time_out within CaptureRequest.
