### ISSUE TITLE
Allocate dedicated setup for CICD

### ISSUE THREAD

**Issue by winstonliu1111** [open-traffic-generator/ixnetwork#83]
Allocate a dedicated testbed with b2b Novus or VMOne port and IxNetwork API server - for CI/CD.
There's already one provided by Andy B, but not sure if it's dedicated and has intended ports.

We also need to determine what IxN API server version and load module we're targetting, so that everyone uses the same during development (to avoid conversations like "reproducible on my setup").

**Comment by ashutshkumr** [comment]
We also need to see if we can stick to linux-only runners, since we have a limit of 2000 minutes per month on linux and 1000 minutes per month on Windows.

https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Comment by ashutshkumr** [comment]
fixed as per `snappi[ixnetwork]==0.3.13`
