### ISSUE TITLE
Add feasibility to ignore packet capture as per user's convenience in utils.start_traffic

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#96]
If packet capture is added as default for all instances of start_traffic, this might create overhead on ixNetwork if continuous traffic is sent

**Comment by ashutshkumr** [comment]
Introduced kwarg `start_capture=True` and `stop_capture=True` for calls to `start_traffic` and `stop_traffic`.

https://github.com/open-traffic-generator/ixnetwork/commit/1d2967c7d97f80a026e745e785eb5d01e62c6d6c
