### ISSUE TITLE
Add test for UDP header with Counter Pattern for UDP src,dst,length and checksum

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#98]
- Add new test script inside tests/udp/
- For each pattern type in list
       - Provide non-default counter pattern values for src port, dst port, length and checksum
       - Validate that src port, dst port, length and checksum are as expected from captured frame

**Comment by ashutshkumr** [comment]
@ANISH-GOTTAPU we won't need to do it for length and checksum. Please open another issue for those (check IPv4 test plan for length, for reference)

**Comment by ANISH-GOTTAPU** [comment]
@ashutshkumr : As discussed, I will add different issue to test length that is being set as per frame size. This test would check the user passed length and checksum values

**Comment by ANISH-GOTTAPU** [comment]
Closed with #113
